# permissions for end users to view nfs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nfs-viewer-role
rules:
- apiGroups:
  - nfs.storage.ibmcloud.ibm.com
  resources:
  - nfs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - nfs.storage.ibmcloud.ibm.com
  resources:
  - nfs/status
  verbs:
  - get
